#!/bin/sh
###################################################
# Write for  Gnu-Linux O.S.x64                    #
# Author      : Cristian Pozzessere               #
# D.A.Page    : http://lnanny.deviantart.com      #
#Git Hub Page : https://github.com/ilnanny        #
#                                                 #
#   _  _                                          # 
#  (_)| | _ __    __ _  _ __   _ __   _   _       #
#  | || || '_ \  / _` || '_ \ | '_ \ | | | |      # 
#  | || || | | || (_| || | | || | | || |_| |      # 
#  |_||_||_| |_| \__,_||_| |_||_| |_| \__, |      #
#                                      |___/      #
#                                                 # 
###################################################
sed -i "s/#e0a55a/#C094C0/g" *.svg

exit 0
 
